// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiga6cGWjdVeb90ugxCsZqY-tayC5Dmcg',
    appId: '1:922890309890:web:dd44fb973dca95f246f21b',
    messagingSenderId: '922890309890',
    projectId: 'little-achievers-academy-demo',
    authDomain: 'little-achievers-academy-demo.firebaseapp.com',
    storageBucket: 'little-achievers-academy-demo.firebasestorage.app',
    measurementId: 'G-C16457H93F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBguA_F0YkYI_DPCWHUop73MaOzeEJJrMI',
    appId: '1:922890309890:android:02c7ee332c06e1a946f21b',
    messagingSenderId: '922890309890',
    projectId: 'little-achievers-academy-demo',
    storageBucket: 'little-achievers-academy-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0WArB-3IFF7bQbQTlcGDGMG2IxEoCQvI',
    appId: '1:922890309890:ios:4ec0f70d01974cad46f21b',
    messagingSenderId: '922890309890',
    projectId: 'little-achievers-academy-demo',
    storageBucket: 'little-achievers-academy-demo.firebasestorage.app',
    iosBundleId: 'com.example.llaSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0WArB-3IFF7bQbQTlcGDGMG2IxEoCQvI',
    appId: '1:922890309890:ios:4ec0f70d01974cad46f21b',
    messagingSenderId: '922890309890',
    projectId: 'little-achievers-academy-demo',
    storageBucket: 'little-achievers-academy-demo.firebasestorage.app',
    iosBundleId: 'com.example.llaSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiga6cGWjdVeb90ugxCsZqY-tayC5Dmcg',
    appId: '1:922890309890:web:208c9bef7c1db17246f21b',
    messagingSenderId: '922890309890',
    projectId: 'little-achievers-academy-demo',
    authDomain: 'little-achievers-academy-demo.firebaseapp.com',
    storageBucket: 'little-achievers-academy-demo.firebasestorage.app',
    measurementId: 'G-JHW8SC45E1',
  );
}
